name: Update latest tag

on:
  schedule:
    cron: "*/20 * * * *"

jobs:
  update:
    runs-on: ubuntu-latest
    if: ${{ secrets.UPDATE_LATEST_TAG == 'true' }}
    steps:
    -
      name: Checkout
      uses: actions/checkout@v3
      with:
        ref: ${{ github.event.repository.default_branch }}
    -
      name: Find latest tag
      run : |
        echo  TAG=$(git describe --tags --abbrev=0)  >>$GITHUB_ENV
    -
      name: Checkout
      uses: actions/checkout@v3
      if: ${{ env.TAG != '' }}
      with:
        ref: ${{ env.TAG }}
    -
      name: Debug
      if: ${{ env.TAG != '' }}
      run : |
        echo  ${{ env.TAG }}
        git status
